version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    build: ./nginx
    ports:
      - "443:80"
    depends_on:
      - "web"

#  app:
#    build: .
#    volumes:
#      - .:/django
#    ports:
#      - 8000:8000
##      - 8080:8000
##      - 8443:8000
##    image: app:django
#    container_name: django_container
#    command: python manage.py runserver 0.0.0.0:8000
